Tables:
  FinancialCovenants:
    CashflowCover:
      regex_chk: 'Cashflow Cover:'
    InterestCover:
    SeniorInterestCover:
    CapitalExpenditure:
    SeniorAdjustedLeverage:
    AdjustedLeverage:
